# Generated by Django 4.0.3 on 2022-06-14 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Order_quantity',
            new_name='order_quantity',
        ),
    ]
