# Generated by Django 4.0.3 on 2022-06-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_order_quantity_order_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('In-progress', 'In-progress'), ('Delivered', 'Delivered')], max_length=225, null=True),
        ),
    ]
