# Generated by Django 4.0.3 on 2022-06-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('In-progress', 'In-progress'), ('Delivered', 'Delivered'), ('Declined', 'Declined')], default='In-progress', max_length=225, null=True),
        ),
    ]
