# Generated by Django 4.0.3 on 2022-06-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
